#docker-compose up --build
version: "3.8"

networks:
  mqtt-net:
    driver: overlay
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 172.100.10.0/24

services:
  mqtt-broker:
    image: eclipse-mosquitto:latest
    user: mosquitto
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    volumes:
      - ./config/:/mosquitto/config/
      - ./log/:/mosquitto/log/
      - data:/mosquitto/data/
    ports:
      - "1883:1883"
      - "9001:9001"
    networks:
      - mqtt-net
    extra_hosts:
      - "mqtt-broker:172.100.10.10"

volumes:
  data:
    name: "mqtt-broker-data"
