version: '3'

services:
  swarm_messager:
    image: eclipse-mosquitto
    command: mosquitto_pub -h mqtt-broker-1 -p 5005 -t test/nem -m "nem yuksek"
    networks:
      - mosquitto-broker-no-swarm_mqtt-network

networks:
  mosquitto-broker-no-swarm_mqtt-network:
    external: true
    # docker-compose up --scale swarm_messager=25 -d