version: '3'

services:
  swarm_messager:
    image: eclipse-mosquitto
    command: mosquitto_pub -h haproxy-lb-swarm -p 1883 -t test/nem -m "nem yuksek"
    networks:
      - getstartedLab_mqtt-net

networks:
  getstartedLab_mqtt-net:
    external: true
    # docker-compose up --scale swarm_messager=25 -d